framework:
    messenger:
        failure_transport: failed

        transports:
            pim:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: pim
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    max_delay: 60000
            dam:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: dam
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    max_delay: 60000
            etl:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: etl
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    max_delay: 60000
            enrichment:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: enrichment
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    max_delay: 60000
            mail:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: mail
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            App\Shared\Message\MediaUploaded: dam
            App\Shared\Message\MediaProcessed: pim
            'App\Pim\Message\*': pim
            'App\Dam\Message\*': dam
            'App\Etl\Message\*': etl
            'App\Enrichment\Message\*': enrichment
            Symfony\Component\Mailer\Messenger\SendEmailMessage: mail
            Symfony\Component\Notifier\Message\ChatMessage: mail
            Symfony\Component\Notifier\Message\SmsMessage: mail

when@test:
    framework:
        messenger:
            transports:
                pim: 'in-memory://'
                dam: 'in-memory://'
                etl: 'in-memory://'
                enrichment: 'in-memory://'
                mail: 'in-memory://'
                failed: 'in-memory://'
