<?php

declare(strict_types=1);

namespace App\Pim\Maquette;

/**
 * Contenu de démonstration de l'éditeur de fiche Lieu.
 *
 * CE FICHIER EST GÉNÉRÉ à partir du handoff « MDM Business Profilers » : les
 * 16 sections, leurs 122 champs, les autorités, les puces et les valeurs
 * suggérées y sont repris tels quels. Ne pas l'éditer à la main — le
 * régénérer si la maquette évolue.
 *
 * Contenu jetable, à supprimer dès qu'un service métier alimente l'écran.
 *
 * @phpstan-type Champ array{label: string, valeur: string, vide: bool, autorite: string, autoriteDot: string, autoriteFg: string, autoriteBg: string, lectureSeule: bool, verrouille: bool, liste: bool, riche: bool, suggerable: bool}
 * @phpstan-type Section array{nom: string, icone: string, completude: int, champs: list<Champ>}
 * @phpstan-type Puce array{0: string, 1: bool}
 * @phpstan-type GroupePuces array{nom: string, puces: list<Puce>}
 */
final class FicheLieuDonnees
{
    /** @var list<Section> */
    public const SECTIONS = [
        [
            'nom' => 'Informations générales',
            'icone' => 'info',
            'completude' => 100,
            'champs' => [
                [
                    'label' => 'Nom du lieu*',
                    'valeur' => 'Jeanne & The Forest - Château de Montvillargenne',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => true,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Typologie*',
                    'valeur' => 'Hôtel - Hôtel 4*',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Groupe et chaîne hôtelière',
                    'valeur' => '-',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Événements de prédilection',
                    'valeur' => 'Chasse au trésor, Défi culinaire type Masterchef, Rallye en 2CV sur Chantilly...',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'ERP',
                    'valeur' => '-',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Site web officiel*',
                    'valeur' => 'https://www.jeanneandtheforest.com/seminaire',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Localisation & accessibilité',
            'icone' => 'mappin',
            'completude' => 83,
            'champs' => [
                [
                    'label' => 'Pays*',
                    'valeur' => 'France',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Rue*',
                    'valeur' => '2 Av. François Mathet',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Code postal*',
                    'valeur' => '60270',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Ville*',
                    'valeur' => 'Gouvieux',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Arrondissement*',
                    'valeur' => '-',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Département*',
                    'valeur' => '60 - Oise',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Région*',
                    'valeur' => 'Hauts-de-France',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Gare(s)',
                    'valeur' => 'Gare de Chantilly-Gouvieux (4 km - 8 min)',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Métro(s)',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'RER(s)',
                    'valeur' => 'RER D - Orry-la-Ville (12 km)',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Tram(s)',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Aéroport(s)',
                    'valeur' => 'Aéroport Charles de Gaulle, CDG (25 km), Aéroport Paris-Beauvais Tillé (40 km)...',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Thématiques & ambiances',
            'icone' => 'confetti',
            'completude' => 60,
            'champs' => [
                [
                    'label' => 'Ambiances',
                    'valeur' => 'Nature, Historique, Cosy',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Thématiques',
                    'valeur' => 'Team building, Incentive',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Style architectural',
                    'valeur' => 'Château XIXᵉ',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Cadre',
                    'valeur' => 'Forêt · 16 hectares',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Vue remarquable',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Atmosphère sonore',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Périodes recommandées',
                    'valeur' => 'Printemps, Automne',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Public cible',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Univers de marque',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Mots-clés SEO',
                    'valeur' => 'séminaire Chantilly, château Oise',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Description',
            'icone' => 'note',
            'completude' => 86,
            'champs' => [
                [
                    'label' => 'Paragraphe de description générale *',
                    'valeur' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => true,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Les plus / atouts 1 *',
                    'valeur' => 'Volutpat',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Les plus / atouts 2 *',
                    'valeur' => 'Lacinia',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Les plus / atouts 3 *',
                    'valeur' => 'Pretium',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Les plus / atouts 4 *',
                    'valeur' => 'Rhoncus',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Les plus / atouts 5 *',
                    'valeur' => 'Pulvinar',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Points d\'intérêt à moins de 15 min à pied',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
        [
            'nom' => 'Hébergement',
            'icone' => 'bed',
            'completude' => 83,
            'champs' => [
                [
                    'label' => 'Nombre de chambres*',
                    'valeur' => '120',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Chambres single',
                    'valeur' => '44',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Chambres double / twin',
                    'valeur' => '68',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Suites',
                    'valeur' => '8',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Chambres PMR',
                    'valeur' => '4',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Classement',
                    'valeur' => '4 étoiles',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Petit-déjeuner inclus',
                    'valeur' => 'Oui',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Wifi en chambre',
                    'valeur' => 'Gratuit',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Climatisation',
                    'valeur' => 'Oui, toutes chambres',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Capacité d\'hébergement totale',
                    'valeur' => '196 personnes',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Hôtels partenaires à proximité',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Politique animaux',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
        [
            'nom' => 'Réunion',
            'icone' => 'userrect',
            'completude' => 100,
            'champs' => [
                [
                    'label' => 'Nombre de salles de réunion*',
                    'valeur' => '9',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Capacité de la plus grande salle en configuration cocktail*',
                    'valeur' => '320',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Capacité de la plus grande salle en configuration Théâtre*',
                    'valeur' => '220',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Surface de la plus petite salle de réunion (en m²)*',
                    'valeur' => '38',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Surface de la plus grande salle de réunion (en m²)*',
                    'valeur' => '220',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Descriptif des salles de séminaires',
                    'valeur' => 'Lorem ipsum dolor sit amet consectetur. Nunc aenean aliquam commodo viverra. Dictum a vel pharetra arcu pulvinar duis tortor. At scelerisque vel fusce tempor. Aliquam ultrices molestie egestas turpis pharetra. Quis nisl neque magna fringilla orci curabitur. Urna blandit dolor erat gravida sed. Faucibus posuere ipsum vel porta dictum tristique velit.',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => true,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Restauration',
            'icone' => 'fork',
            'completude' => 100,
            'champs' => [
                [
                    'label' => 'Nom du restaurant*',
                    'valeur' => 'Restaurant Villa M',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Typologie de restaurant*',
                    'valeur' => 'Bistronomique',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Type de cuisine*',
                    'valeur' => 'Française',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Spécificité alimentaire*',
                    'valeur' => 'Produits locaux',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Type d\'événement*',
                    'valeur' => 'Brunch, Déjeuner assis, Dîner assis',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Site officiel*',
                    'valeur' => 'https://www.jeanneandtheforest.com/seminaire',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Loisirs & team building',
            'icone' => 'bike',
            'completude' => 0,
            'champs' => [
                [
                    'label' => 'Nom de l\'activité*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Langue parlée*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Thématique de l\'activité*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Environnement de l\'activité*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Prestation à partir de combien personne ?*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Prestation jusqu\'à combien de personne ?*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Durée de la prestation ?*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
        [
            'nom' => 'Services & équipements',
            'icone' => 'lectern',
            'completude' => 33,
            'champs' => [

            ],
        ],
        [
            'nom' => 'RSE',
            'icone' => 'plant',
            'completude' => 18,
            'champs' => [
                [
                    'label' => 'Certification environnementale',
                    'valeur' => 'Clef Verte',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Score RSE interne',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Tri des déchets',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Produits d\'entretien écologiques',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Énergie renouvelable',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Circuit court restauration',
                    'valeur' => 'Oui',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Politique anti-gaspillage',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Mobilité douce',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Accessibilité sociale',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Bilan carbone',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Charte RSE signée',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
        [
            'nom' => 'Tarifs',
            'icone' => 'euro',
            'completude' => 75,
            'champs' => [
                [
                    'label' => 'Type de produit à créer*',
                    'valeur' => 'Lorem ipsum dolor sit amet consectetur sollicitudin.',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Nom du produit*',
                    'valeur' => 'Lorem ipsum dolor sit amet consectetur sollicitudin.',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Contenu de la formule*',
                    'valeur' => 'Sélectionnez les options',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => true,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Prix HT*',
                    'valeur' => '361,82€',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Montant TVA',
                    'valeur' => 'Montant TVA',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Pour combien de personnes*',
                    'valeur' => '4',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Quantité minimum de commande*',
                    'valeur' => '4',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Quantité maximum de commande*',
                    'valeur' => '4',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Nombre de participants minimum*',
                    'valeur' => '4',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Date limite de commande*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Heure limite de commande*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Délai minimum entre la commande et le créneau livraison*',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
        [
            'nom' => 'Médias',
            'icone' => 'images',
            'completude' => 60,
            'champs' => [

            ],
        ],
        [
            'nom' => 'Booster ma visibilité',
            'icone' => 'rocket',
            'completude' => 25,
            'champs' => [

            ],
        ],
        [
            'nom' => 'Facturation & partenariat',
            'icone' => 'money',
            'completude' => 100,
            'champs' => [
                [
                    'label' => 'Pays',
                    'valeur' => 'France',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Raison sociale',
                    'valeur' => 'Raison sociale',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Forme juridique',
                    'valeur' => 'Forme juridique',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Rue postale',
                    'valeur' => '2 rue des Marguerites',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Complément d\'adresse',
                    'valeur' => '-',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Code postal',
                    'valeur' => '75001',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Ville',
                    'valeur' => 'Paris',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'N° de SIRET',
                    'valeur' => '87453920100045',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'N° de TVA',
                    'valeur' => 'FR12345678901',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'TVA au débit ou à l\'encaissement',
                    'valeur' => 'TVA au débit ou à l\'encaissement',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'BIC',
                    'valeur' => 'BNCMFR21',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'IBAN',
                    'valeur' => 'FR76 XXXX XXXX XXXXX XXXX XX21',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Date d\'acompte',
                    'valeur' => 'Signature à J-60',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => '% d\'accompte',
                    'valeur' => '30%',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Date du paiement',
                    'valeur' => '7 jours',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => '% sur le CA global',
                    'valeur' => '15%',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Paiement',
                    'valeur' => 'Déduction sur le solde',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Signé le',
                    'valeur' => '12/11/2025',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Signataire',
                    'valeur' => 'Clémence Philips - clemence.philips@gmail.com',
                    'vide' => false,
                    'autorite' => 'Salesforce',
                    'autoriteDot' => 'primary-marine',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'neutral-200',
                    'lectureSeule' => true,
                    'verrouille' => true,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Collaborateurs',
            'icone' => 'users',
            'completude' => 89,
            'champs' => [
                [
                    'label' => 'Nom*',
                    'valeur' => 'Léa',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Prénom*',
                    'valeur' => 'Garnier',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Email*',
                    'valeur' => 'lea.bernard@email.com',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Téléphone*',
                    'valeur' => '07 58 92 41 36',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Rôle',
                    'valeur' => 'Manager',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Adresse email*',
                    'valeur' => 'Adresse email',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Dernière connexion au portail',
                    'valeur' => 'hier, 09:12',
                    'vide' => false,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
                [
                    'label' => 'Comptes en attente d\'activation',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'MDM',
                    'autoriteDot' => 'primary-turquoise',
                    'autoriteFg' => 'primary-marine',
                    'autoriteBg' => 'primary-bleu-clair',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Notifications activées',
                    'valeur' => 'Devis, Avis',
                    'vide' => false,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => false,
                ],
            ],
        ],
        [
            'nom' => 'Templates de message',
            'icone' => 'layout',
            'completude' => 0,
            'champs' => [
                [
                    'label' => 'Template 1',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Template 2',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Template 3',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Template 4',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
                [
                    'label' => 'Template 5',
                    'valeur' => 'Non renseigné',
                    'vide' => true,
                    'autorite' => 'Prestataire',
                    'autoriteDot' => 'secondary-p-che',
                    'autoriteFg' => 'neutral-900',
                    'autoriteBg' => 'secondary-p-che-p-le',
                    'lectureSeule' => false,
                    'verrouille' => false,
                    'liste' => false,
                    'riche' => false,
                    'suggerable' => true,
                ],
            ],
        ],
    ];

    /** @var array<string, list<GroupePuces>> */
    public const GROUPES_PUCES = [
        'Services & équipements' => [
            [
                'nom' => 'Services',
                'puces' => [
                    ['Voiturier', true],
                    ['Navette Gratuite', true],
                    ['Vestiaire/Bagagerie', true],
                    ['Service pressing', false],
                    ['Réception 24h/24', false],
                    ['Photocopie', false],
                    ['Borne de recharge pour véhicule électriques', true],
                    ['Room service', false],
                ],
            ],
            [
                'nom' => 'Techniques & réunion',
                'puces' => [
                    ['Wi-fi gratuit', false],
                    ['Connexion internet filaire', false],
                    ['Paper Board', false],
                    ['Vidéo-Projecteur / TV', false],
                    ['Technicien AV sur place', false],
                    ['Écran LCD', false],
                    ['Micro', false],
                    ['Sonorisation', false],
                    ['Blocs-notes & stylo', false],
                    ['Climatisation salles', false],
                    ['Cabine de traduction', true],
                    ['Visio conférence', true],
                    ['Click share', true],
                    ['Fontaines à eau', true],
                ],
            ],
            [
                'nom' => 'Installation',
                'puces' => [
                    ['Amphithéatre', false],
                    ['Fumoir', true],
                    ['Jardin / Parc', true],
                    ['Rooftop', false],
                    ['Terrasse / Cour intérieure', false],
                    ['Balcon', false],
                    ['Cave de dégustation', false],
                    ['Plage privée', false],
                    ['Espace de coworking', false],
                    ['Parking', true],
                    ['Business center', true],
                    ['Ascenseur', false],
                ],
            ],
            [
                'nom' => 'Bien-être',
                'puces' => [
                    ['Thalasso', false],
                    ['Piscine intérieure', false],
                    ['Piscine extérieure', true],
                    ['Spa et centre de bien-être', true],
                    ['Sauna', true],
                    ['Hammam', false],
                    ['Jaccuzi / Bain à remous', false],
                    ['Centre de remise en forme', false],
                    ['Fitness / Salle de sport', false],
                    ['Massage', false],
                    ['Espace détente', false],
                ],
            ],
        ],
    ];

    /** @var array<string, string> Valeurs proposées par l'IA, par libellé de champ */
    public const VALEURS_SUGGEREES = [
        'Arrondissement*' => 'Arrondissement de Senlis',
        'Date limite de commande*' => 'J-3 avant le créneau de livraison',
        'Heure limite de commande*' => '16:00',
        'Délai minimum entre la commande et le créneau livraison*' => '72 heures',
        'Comptes en attente d\'activation' => '2 comptes · relance envoyée le 12/07',
        'Template 1' => 'Confirmation de réservation — FR',
        'Template 2' => 'Demande de devis — accusé de réception',
        'Template 3' => 'Relance après visite du lieu',
        'Template 4' => 'Remerciement post-événement',
        'Groupe et chaîne hôtelière' => 'Groupe Tiara Hotels & Resorts',
        'ERP' => 'Type O · 4e catégorie',
        'Vue remarquable' => 'Forêt et pièce d\'eau',
        'Atmosphère sonore' => 'Calme · aucun axe routier à moins de 800 m',
        'Public cible' => 'Comités de direction, séminaires incentive',
        'Univers de marque' => 'Élégance discrète · patrimoine',
        'Titre court EN' => 'Charming château in the forest of Chantilly',
        'Description longue EN' => 'A 19th-century estate set in 16 hectares of forest, 40 minutes from Paris.',
        'Accroche commerciale' => 'Le calme de la forêt, à 40 minutes de Paris',
        'Description des espaces FR' => 'Neuf salles de réunion en enfilade ouvertes sur le parc',
        'Hôtels partenaires à proximité' => 'Auberge du Jeu de Paume · Dolce Chantilly',
        'Politique animaux' => 'Acceptés en chambre, supplément 25 €',
        'Score RSE interne' => '72 / 100',
        'Tri des déchets' => '5 flux triés',
        'Produits d\'entretien écologiques' => 'Écolabel européen',
        'Énergie renouvelable' => 'Électricité 100 % renouvelable',
        'Politique anti-gaspillage' => 'Don des invendus · convention locale',
        'Mobilité douce' => 'Navette gare · 12 bornes de recharge',
        'Accessibilité sociale' => 'Tarif associatif sur demande',
        'Bilan carbone' => 'Réalisé en 2024',
        'Charte RSE signée' => 'Oui, mars 2024',
        'Nom de l\'activité*' => 'Chasse au trésor en forêt',
        'Langue parlée*' => 'Français, Anglais',
        'Thématique de l\'activité*' => 'Aventure · cohésion',
        'Environnement de l\'activité*' => 'Extérieur · forêt',
        'Gare(s)' => 'Gare de Chantilly-Gouvieux (8 km - 12 min)',
        'Métro(s)' => 'Aucun',
        'Tram(s)' => 'Aucun',
        'Mots-clés SEO' => 'séminaire Chantilly, château Oise',
    ];

    /** @var array{tier: string, level: string, value: string, lines: list<string>} */
    public const FORMULE = [
        'tier' => 'Pack Découverte',
        'level' => 'Niveau gratuit',
        'value' => '0%',
        'lines' => [
            'Référencement sur le site businessprofilers.com',
            '1 communication newsletter groupée',
        ],
    ];

    public const ACTION_MARKETING = '1 publication Linkedin';

    /** @var list<string> */
    public const ONGLETS_MEDIAS = ['Photos', 'Plans', 'Supports commerciaux'];
}
